name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 11
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: pnpm install --frozen-lockfile
      - run: bun test
      
      - run: pnpm --filter=!dashboard build
      
      - run: pnpm --filter=!dashboard exec tsc --noEmit